//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfw.ServiceAgent.EntityServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/pfw.SDK.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pfw.ServiceAgent.EntityServiceReference.LogInRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pfw.ServiceAgent.EntityServiceReference.EntityRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAgentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationToken {
            get {
                return this.AuthenticationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenField, value) != true)) {
                    this.AuthenticationTokenField = value;
                    this.RaisePropertyChanged("AuthenticationToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerKey {
            get {
                return this.ManagerKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerKeyField, value) != true)) {
                    this.ManagerKeyField = value;
                    this.RaisePropertyChanged("ManagerKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestKey {
            get {
                return this.RequestKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestKeyField, value) != true)) {
                    this.RequestKeyField = value;
                    this.RaisePropertyChanged("RequestKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAgent {
            get {
                return this.UserAgentField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAgentField, value) != true)) {
                    this.UserAgentField = value;
                    this.RaisePropertyChanged("UserAgent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogInRequest", Namespace="http://schemas.datacontract.org/2004/07/pfw.SDK.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LogInRequest : pfw.ServiceAgent.EntityServiceReference.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForceLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ForceLogin {
            get {
                return this.ForceLoginField;
            }
            set {
                if ((this.ForceLoginField.Equals(value) != true)) {
                    this.ForceLoginField = value;
                    this.RaisePropertyChanged("ForceLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineName {
            get {
                return this.MachineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNameField, value) != true)) {
                    this.MachineNameField = value;
                    this.RaisePropertyChanged("MachineName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSUserName {
            get {
                return this.OSUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OSUserNameField, value) != true)) {
                    this.OSUserNameField = value;
                    this.RaisePropertyChanged("OSUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityRequest", Namespace="http://schemas.datacontract.org/2004/07/pfw.SDK.DataContracts")]
    [System.SerializableAttribute()]
    public partial class EntityRequest : pfw.ServiceAgent.EntityServiceReference.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pfw.ServiceAgent.EntityServiceReference.EntityManager EntityManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pfw.ServiceAgent.EntityServiceReference.EntityTypeName EntityTypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((this.EntityIdField.Equals(value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pfw.ServiceAgent.EntityServiceReference.EntityManager EntityManager {
            get {
                return this.EntityManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityManagerField, value) != true)) {
                    this.EntityManagerField = value;
                    this.RaisePropertyChanged("EntityManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pfw.ServiceAgent.EntityServiceReference.EntityTypeName EntityTypeName {
            get {
                return this.EntityTypeNameField;
            }
            set {
                if ((this.EntityTypeNameField.Equals(value) != true)) {
                    this.EntityTypeNameField = value;
                    this.RaisePropertyChanged("EntityTypeName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityManager", Namespace="http://schemas.datacontract.org/2004/07/pfw.Controller.Manager")]
    [System.SerializableAttribute()]
    public partial class EntityManager : pfw.ServiceAgent.EntityServiceReference.Manager {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityTypeName", Namespace="http://schemas.datacontract.org/2004/07/pfw.Controller.Base")]
    public enum EntityTypeName : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Item = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manager", Namespace="http://schemas.datacontract.org/2004/07/pfw.Controller.Manager")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pfw.ServiceAgent.EntityServiceReference.EntityManager))]
    public partial class Manager : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private pfw.ServiceAgent.EntityServiceReference.EntityTypeName EntityTypeNamek__BackingFieldField;
        
        private System.Guid ManagerGuidk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EntityTypeName>k__BackingField", IsRequired=true)]
        public pfw.ServiceAgent.EntityServiceReference.EntityTypeName EntityTypeNamek__BackingField {
            get {
                return this.EntityTypeNamek__BackingFieldField;
            }
            set {
                if ((this.EntityTypeNamek__BackingFieldField.Equals(value) != true)) {
                    this.EntityTypeNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("EntityTypeNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ManagerGuid>k__BackingField", IsRequired=true)]
        public System.Guid ManagerGuidk__BackingField {
            get {
                return this.ManagerGuidk__BackingFieldField;
            }
            set {
                if ((this.ManagerGuidk__BackingFieldField.Equals(value) != true)) {
                    this.ManagerGuidk__BackingFieldField = value;
                    this.RaisePropertyChanged("ManagerGuidk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/pfw.SDK.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pfw.ServiceAgent.EntityServiceReference.LogInResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pfw.ServiceAgent.EntityServiceReference.EntityResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRequestSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastErrorTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessingServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ServerProcessingTicksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorIDField, value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRequestSuccessful {
            get {
                return this.IsRequestSuccessfulField;
            }
            set {
                if ((this.IsRequestSuccessfulField.Equals(value) != true)) {
                    this.IsRequestSuccessfulField = value;
                    this.RaisePropertyChanged("IsRequestSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastErrorDetails {
            get {
                return this.LastErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.LastErrorDetailsField, value) != true)) {
                    this.LastErrorDetailsField = value;
                    this.RaisePropertyChanged("LastErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastErrorMessage {
            get {
                return this.LastErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.LastErrorMessageField, value) != true)) {
                    this.LastErrorMessageField = value;
                    this.RaisePropertyChanged("LastErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastErrorTitle {
            get {
                return this.LastErrorTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.LastErrorTitleField, value) != true)) {
                    this.LastErrorTitleField = value;
                    this.RaisePropertyChanged("LastErrorTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessingServer {
            get {
                return this.ProcessingServerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessingServerField, value) != true)) {
                    this.ProcessingServerField = value;
                    this.RaisePropertyChanged("ProcessingServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestKey {
            get {
                return this.RequestKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestKeyField, value) != true)) {
                    this.RequestKeyField = value;
                    this.RaisePropertyChanged("RequestKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ServerProcessingTicks {
            get {
                return this.ServerProcessingTicksField;
            }
            set {
                if ((this.ServerProcessingTicksField.Equals(value) != true)) {
                    this.ServerProcessingTicksField = value;
                    this.RaisePropertyChanged("ServerProcessingTicks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogInResponse", Namespace="http://schemas.datacontract.org/2004/07/pfw.SDK.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LogInResponse : pfw.ServiceAgent.EntityServiceReference.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityResponse", Namespace="http://schemas.datacontract.org/2004/07/pfw.SDK.DataContracts")]
    [System.SerializableAttribute()]
    public partial class EntityResponse : pfw.ServiceAgent.EntityServiceReference.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pfw.ServiceAgent.EntityServiceReference.EntityTypeName EntityTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ManagerGuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((this.EntityIdField.Equals(value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pfw.ServiceAgent.EntityServiceReference.EntityTypeName EntityTypeName {
            get {
                return this.EntityTypeNameField;
            }
            set {
                if ((this.EntityTypeNameField.Equals(value) != true)) {
                    this.EntityTypeNameField = value;
                    this.RaisePropertyChanged("EntityTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ManagerGuid {
            get {
                return this.ManagerGuidField;
            }
            set {
                if ((this.ManagerGuidField.Equals(value) != true)) {
                    this.ManagerGuidField = value;
                    this.RaisePropertyChanged("ManagerGuid");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntityServiceReference.IEntityService")]
    public interface IEntityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/Entity", ReplyAction="http://tempuri.org/IEntityService/EntityResponse")]
        pfw.ServiceAgent.EntityServiceReference.EntityResponse Entity(pfw.ServiceAgent.EntityServiceReference.EntityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/Layout", ReplyAction="http://tempuri.org/IEntityService/LayoutResponse")]
        pfw.ServiceAgent.EntityServiceReference.EntityResponse Layout(pfw.ServiceAgent.EntityServiceReference.EntityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LogIn", ReplyAction="http://tempuri.org/IEntityService/LogInResponse")]
        pfw.ServiceAgent.EntityServiceReference.LogInResponse LogIn(pfw.ServiceAgent.EntityServiceReference.LogInRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntityServiceChannel : pfw.ServiceAgent.EntityServiceReference.IEntityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntityServiceClient : System.ServiceModel.ClientBase<pfw.ServiceAgent.EntityServiceReference.IEntityService>, pfw.ServiceAgent.EntityServiceReference.IEntityService {
        
        public EntityServiceClient() {
        }
        
        public EntityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public pfw.ServiceAgent.EntityServiceReference.EntityResponse Entity(pfw.ServiceAgent.EntityServiceReference.EntityRequest request) {
            return base.Channel.Entity(request);
        }
        
        public pfw.ServiceAgent.EntityServiceReference.EntityResponse Layout(pfw.ServiceAgent.EntityServiceReference.EntityRequest request) {
            return base.Channel.Layout(request);
        }
        
        public pfw.ServiceAgent.EntityServiceReference.LogInResponse LogIn(pfw.ServiceAgent.EntityServiceReference.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
    }
}
